config/routes.rb
Rails.application.routes.draw do
  resources :hosts
  post 'hosts/new'
  get  'hosts/new'
  get  'inventory/dash_board'
  post 'inventory/dash_board'  

  resources :users
  get 'home/index'
  get 'inventory/inventario'
 
  
  resources :inventory
  post 'inventory/verificarHost' 
  get  'inventory/verificarHost' 

  

    root 'users#new'
  

end

app/models/host.rb
class Host < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
    
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end
  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: 'Host was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:nombre, :usuario, :contraseña, :clave)
    end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController

	
  def inventario

  end


  def verificarHost
     
    if (params[:host] == "otro_host") 
  	  redirect_to :controller => "hosts" , :action => "new"
    else
      redirect_to  :action => "dash_board" 
    end
  end	

  def dash_board
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    existe = User.first
    if (existe != nil )
      redirect_to  :controller => "inventory", :action => "inventario"
    end    
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user, :pass)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Bienvenido al Sistema de Control de Configuraciones e Infraestructura</h1>

<div>
	<p>Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum</p>
</div>
<div>
	<h2>La aplicación esta lista para iniciar la configuración</h2>
</div>
<div>
	<H3>Por favor crea un usuario y contraseña para asegurar un acceso seguro</H3>
</div>
<div>
	<%= label_tag(:q, "Usuario:") %>
	<%= text_field_tag(:q) %>
	<br>
	<%= label_tag(:q, "Contraseña:") %>
	<%= text_field_tag(:q) %>
	<br>
	<%= label_tag(:q, "Repetir Contraseña:") %>
	<%= text_field_tag(:q) %>
	<br>	
	<%= button_tag %>
</div>

app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :contraseña %><br>
    <%= f.text_field :contraseña %>
  </div>
  <div class="field">
    <%= f.label :clave %><br>
    <%= f.text_area :clave %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hosts</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Usuario</th>
      <th>Contraseña</th>
      <th>Clave</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.nombre %></td>
        <td><%= host.usuario %></td>
        <td><%= host.contraseña %></td>
        <td><%= host.clave %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host', new_host_path %>

app/views/hosts/new.html.erb
<h1>Bienvenido al sistema de control de configuraciones e infraestructura</h1>

<h2>configurando host de Ejecucion...</h2>
<h3>Introduzca  información del host de ejecución de instrucciones</h3>

<%= render 'form' %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @host.nombre %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @host.usuario %>
</p>

<p>
  <strong>Contraseña:</strong>
  <%= @host.contraseña %>
</p>

<p>
  <strong>Clave:</strong>
  <%= @host.clave %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/inventory/dash_board.html.erb
<h1>Bienvenido al sistema de control de configuración e infraestructura</h1>
<h2>Configurando inventario...</h2>
<h3>Introduzca la información del inventario</h3>

app/views/inventory/inventario.html.erb
<h1>Bienvenido al sistema de control de configuración e infraestructura</h1>
<h2>Configurando inventario...</h2>
<h3>Introduzca la información del inventario</h3>

 <%= form_tag({controller: "inventory", action: "verificarHost"}, method: "POST") do %>
  <%= label_tag(:q, "Nombre del inventario") %>
  <br>
  <%= text_field_tag(:q) %>
  <br>
  <%= label_tag(:p, "Repositorio de Versiones") %>
  <br>
  <%= text_field_tag(:p) %>
  <br>
  <%= submit_tag("Comprobar") %>
  <br>
  <h3>Host de Ejecución</h3>
  <p> Otro Host
   <%= radio_button_tag :host,  "otro_host", :checked => true %>  </p>
  <p> Este Host <%= radio_button_tag :host,  "este_host" %>  </p>
  <br>
  <%= submit_tag("Siguiente") %>
 <% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProyecAnsible</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :user, :required => true, :placeholder => 'ingrese un usuario' %>
  </div>
  <div class="field">
    <%= f.label :contraseña %><br>
    <%= f.password_field :pass, :required => true, :placeholder => 'ingrese una contraseña'  %>
  </div>
  <div class="field">
    <%= f.label ("repetir contraseña") %><br>
    <%= f.password_field :pass, :required => true, :class => 'passControl', :placeholder => 'repita su contraseña'%>
  </div>  

   <div class="field">
     <%= f.submit :crear, :id => 'botonControl', :disabled => 'true' %> 
   </div> 
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user %></td>
        <td><%= user.pass %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="contenedor">
<h1>Bienvenido al Sistema de Control de Configuraciones e Infraestructura</h1>

<div>
	<p>El Sistema de Control de Configuraciones e Infraestructura permite una visualización del estado de los nodos de la empresa, ver que servicios activos y orquestar la configuración con ansible </p>
</div>
</div>
<div>
	<h2 class="titulo">La aplicación esta lista para iniciar la configuración</h2>
</div>
<div>
	<H3>Por favor crea un usuario y contraseña para asegurar un acceso seguro</H3>
</div>

<div class="formulario">
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user %>
</p>

<p>
  <strong>Pass:</strong>
  <%= @user.pass %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>